artifact_location: file:///C:/Users/LENOVO/Downloads/SMSL_LatifahArumS/Membangun_model/mlruns_local/0
creation_time: 1749113527259
experiment_id: '0'
last_update_time: 1749113527259
lifecycle_stage: active
name: Default
